/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaproyecto;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.StringTokenizer;

/**
 *
 * @author PERLA
 */
public class SumaDiferencia extends javax.swing.JFrame {

    /**
     * Creates new form SumaDiferencia
     */
    public SumaDiferencia() {
        initComponents();
        this.setTitle("Suma/Diferencia");
        this.setLocationRelativeTo(null);
         Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ipn.png"));
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("x(n)");

        jLabel2.setText("y(n)");

        jTextField1.setText("1,2,3,4,5,6");

        jTextField2.setText("1,2,3");

        jLabel3.setText("x(n)+y(n)");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton1.setText("Suma");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Diferencia");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Regresar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setText("n(0)=");

        jLabel5.setText("n(0)=");

        jLabel6.setText("n(0)=");

        jTextField4.setText("1");

        jTextField5.setText("2");

        jLabel7.setText("Ingrese las series x(n) y y(n), asi como indicando el indice el cual esta en el origen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Menu m=new Menu();
        m.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabel3.setText("x(n)+y(n)");
        String x=jTextField1.getText();
        String y=jTextField2.getText();
        String coma;
        ArrayList<Double> xi=new ArrayList();
        ArrayList<Double> yi=new ArrayList();
        ArrayList<Double> hi=new ArrayList();
        StringTokenizer st1 = new StringTokenizer(x,",",true);
        System.out.println("Hay un total de: "+st1.countTokens()+" tokens.");
        Integer i=0;
        Double indicex=0.0,indicey=0.0,indiceh=0.0;
        Double indiceres=0.0;
        Integer nx = null,ny=null,nh=null,nfx=null,nfy=null,nfh=null;
        Integer nix=null,niy=null,nih=null;
        while (st1.hasMoreTokens()) {
            coma=st1.nextToken();
            if(!coma.equals(",")){
                xi.add(Double.parseDouble(coma));
                System.out.println(xi.get(i));
                i++;
            }
        } 
        indicex=Double.parseDouble(jTextField4.getText());
        for(i=0;i<xi.size();i++)
            if(xi.get(i).equals(indicex))
                nx=i;
        nfx=i-nx-1;
        nix=nx;
        System.out.println("indice x(n): "+nx);
        i=0;
        StringTokenizer st2 = new StringTokenizer(y,",",true);
        System.out.println("Hay un total de: "+st2.countTokens()+" tokens.");
        while (st2.hasMoreTokens()) {
            coma=st2.nextToken();
            if(!coma.equals(",")){
             yi.add(Double.parseDouble(coma));
                System.out.println(yi.get(i));   
                i++;
            }
        } 
        indicey=Double.parseDouble(jTextField5.getText());
        for(i=0;i<yi.size();i++)
            if(yi.get(i).equals(indicey))
                ny=i;
        nfy=i-ny-1;
        niy=ny;
        System.out.println("indice y(n): "+ny);
        /*  seleccionamos a la funcion movil h(n) */
        if(xi.size()<yi.size()){
            hi=xi;
            indiceh=indicex;
            nh=nx;
            nfh=nfx;
            nih=nix;
            
            xi=yi;
            indicex=indicey;
            nx=ny;
            nfx=nfy;
            nix=niy;
            
        }
        else{
            hi=yi;
            indiceh=indicey;
            nfh=nfy;
            nih=niy;
            nh=ny;
        } 
        System.out.println("indice h(n): "+nfx);
        System.out.println("indice h(n): "+nfh);
        
        Integer longitud=0;
        if(nfx>nfh)
            longitud+=nfx;
        else
            longitud+=nfh;
        if(nix>niy)
            longitud+=nix;
        else
            longitud+=nih;
        longitud++;
        System.out.println("Longitud del resultado: "+longitud);
        Double[] operadorx=new Double[longitud];
        Double[] operadorh=new Double[longitud];
        Double[] resultado=new Double[longitud];
        System.out.println("operador x: "+operadorx.length);
        System.out.println("operador y: "+operadorh.length);
        Integer cix=0,cih=0,cfx=0,cfh=0,ix=0,ih=0;
         Integer cerosiniciox=0,cerosinicioh=0,cerosfinx=0,cerosfinh=0;
        if(nix<nih)
               cerosiniciox=nih-nix;
        else
            cerosinicioh=nix-nih;
        if(nfx<nfh)
            cerosfinx=nfh-nfx;
        else
            cerosfinh=nfx-nfh;
        
        
        System.out.println("ceros inicio para x: "+cerosiniciox);
        System.out.println("ceros inicio para h: "+cerosinicioh);
        System.out.println("ceros fin para x: "+cerosfinx);
        System.out.println("ceros fin para h: "+cerosfinh);
        for(i=0;i<longitud;i++){
            if(cix<cerosiniciox){
                operadorx[i]=0.0;
                cix++;
            }else if(ix<xi.size()){
               operadorx[i]=xi.get(ix);
                ix++;
            }
            else{
                operadorx[i]=0.0;
            }
            if(cih<cerosinicioh){
                operadorh[i]=0.0;
                cih++;
            }else if(ih<hi.size()){
               operadorh[i]=hi.get(ih);
                ih++;
            }
            else{
                operadorh[i]=0.0;
            }
        }
        for(i=0;i<longitud;i++){
            System.out.print(" "+operadorx[i]);
        }
        System.out.println("");
        for(i=0;i<longitud;i++){
            System.out.print(" "+operadorh[i]);
        }
        for(i=0;i<longitud;i++)
            resultado[i]=operadorx[i]+operadorh[i];
        String res="";
        for(i=0;i<longitud;i++)
            if(i.equals(longitud-1)){
            res+=resultado[i];
            }
            else{
            res+=resultado[i]+",";
            }
        nh=nx+cerosiniciox;
        jTextField3.setText(res);
        jTextField6.setText(resultado[nh].toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jLabel3.setText("x(n)-y(n)");
        String x=jTextField1.getText();
        String y=jTextField2.getText();
        String coma;
        ArrayList<Double> xi=new ArrayList();
        ArrayList<Double> yi=new ArrayList();
        ArrayList<Double> hi=new ArrayList();
        StringTokenizer st1 = new StringTokenizer(x,",",true);
        System.out.println("Hay un total de: "+st1.countTokens()+" tokens.");
        Integer i=0;
        Double indicex=0.0,indicey=0.0,indiceh=0.0;
        Double indiceres=0.0;
        Integer nx = null,ny=null,nh=null,nfx=null,nfy=null,nfh=null;
        Integer nix=null,niy=null,nih=null;
        while (st1.hasMoreTokens()) {
            coma=st1.nextToken();
            if(!coma.equals(",")){
                xi.add(Double.parseDouble(coma));
                System.out.println(xi.get(i));
                i++;
            }
        } 
        indicex=Double.parseDouble(jTextField4.getText());
        for(i=0;i<xi.size();i++)
            if(xi.get(i).equals(indicex))
                nx=i;
        nfx=i-nx-1;
        nix=nx;
        System.out.println("indice x(n): "+nx);
        i=0;
        StringTokenizer st2 = new StringTokenizer(y,",",true);
        System.out.println("Hay un total de: "+st2.countTokens()+" tokens.");
        while (st2.hasMoreTokens()) {
            coma=st2.nextToken();
            if(!coma.equals(",")){
             yi.add(Double.parseDouble(coma));
                System.out.println(yi.get(i));   
                i++;
            }
        } 
        indicey=Double.parseDouble(jTextField5.getText());
        for(i=0;i<yi.size();i++)
            if(yi.get(i).equals(indicey))
                ny=i;
        nfy=i-ny-1;
        niy=ny;
        System.out.println("indice y(n): "+ny);
        /*  seleccionamos a la funcion movil h(n) */
        if(xi.size()<yi.size()){
            hi=xi;
            indiceh=indicex;
            xi=yi;
            indicex=indicey;
            nfh=nfx;
            nih=nix;
            nh=nx;
        }
        else{
            hi=yi;
            indiceh=indicey;
            nfh=nfy;
            nih=niy;
            nh=ny;
        } 
        System.out.println("indice h(n): "+nfx);
        System.out.println("indice h(n): "+nfh);
        
        Integer longitud=0;
        if(nfx>nfh)
            longitud+=nfx;
        else
            longitud+=nfy;
        if(nix>niy)
            longitud+=nix;
        else
            longitud+=niy;
        longitud++;
        System.out.println("Longitud del resultado: "+longitud);
        Double[] operadorx=new Double[longitud];
        Double[] operadorh=new Double[longitud];
        Double[] resultado=new Double[longitud];
        System.out.println("operador x: "+operadorx.length);
        System.out.println("operador y: "+operadorh.length);
        Integer cix=0,cih=0,cfx=0,cfh=0,ix=0,ih=0;
         Integer cerosiniciox=0,cerosinicioh=0,cerosfinx=0,cerosfinh=0;
        if(nix<nih)
               cerosiniciox=nih-nix;
        else
            cerosinicioh=nix-nih;
        if(nfx<nfh)
            cerosfinx=nfh-nfx;
        else
            cerosfinh=nfx-nfh;
        
        
        System.out.println("ceros inicio para x: "+cerosiniciox);
        System.out.println("ceros inicio para h: "+cerosinicioh);
        System.out.println("ceros fin para x: "+cerosfinx);
        System.out.println("ceros fin para h: "+cerosfinh);
        for(i=0;i<longitud;i++){
            if(cix<cerosiniciox){
                operadorx[i]=0.0;
                cix++;
            }else if(ix<xi.size()){
               operadorx[i]=xi.get(ix);
                ix++;
            }
            else{
                operadorx[i]=0.0;
            }
            if(cih<cerosinicioh){
                operadorh[i]=0.0;
                cih++;
            }else if(ih<hi.size()){
               operadorh[i]=hi.get(ih);
                ih++;
            }
            else{
                operadorh[i]=0.0;
            }
        }
        for(i=0;i<longitud;i++){
            System.out.print(" "+operadorx[i]);
        }
        System.out.println("");
        for(i=0;i<longitud;i++){
            System.out.print(" "+operadorh[i]);
        }
        for(i=0;i<longitud;i++)
            resultado[i]=operadorx[i]-operadorh[i];
        String res="";
        for(i=0;i<longitud;i++)
            if(i.equals(longitud-1)){
            res+=resultado[i];
            }
            else{
            res+=resultado[i]+",";
            }
        nh=nx+cerosiniciox;
        jTextField3.setText(res);
        jTextField6.setText(resultado[nh].toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jLabel3.setText("x(n)+y(n)");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SumaDiferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SumaDiferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SumaDiferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SumaDiferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SumaDiferencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
