/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaproyecto;

import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.StringTokenizer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.NumberTickUnit;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author MiguelAngel
 */
public class Diezmacion extends javax.swing.JFrame {

    /**
     * Creates new form Diezmacion
     */
    public Diezmacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nd = new javax.swing.JTextField();
        cn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        diezmar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        origen = new javax.swing.JTextField();
        interpolar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resd = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        resi = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("K:");

        jLabel2.setText("x(n):");

        jLabel3.setText("x(kn):");

        diezmar.setText("Diezmación");
        diezmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diezmarActionPerformed(evt);
            }
        });

        jLabel4.setText("Intervalo de inicio:");

        interpolar.setText("Interpolación");
        interpolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interpolarActionPerformed(evt);
            }
        });

        jLabel5.setText("x(n/k):");

        resd.setEditable(false);
        resd.setColumns(20);
        resd.setRows(5);
        jScrollPane1.setViewportView(resd);

        resi.setEditable(false);
        resi.setColumns(20);
        resi.setRows(5);
        jScrollPane2.setViewportView(resi);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(diezmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(interpolar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(origen, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                    .addComponent(cn)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(origen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diezmar)
                            .addComponent(interpolar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diezmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diezmarActionPerformed
        diezmar();
    }//GEN-LAST:event_diezmarActionPerformed

    private void interpolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interpolarActionPerformed
        interpolar();
    }//GEN-LAST:event_interpolarActionPerformed

    
    public void diezmar(){
        int k=Integer.parseInt(nd.getText());
        int j=0;
        int s=0;
        int f=0;
        Double inicio=Double.parseDouble(origen.getText());
        Integer i=0;
        String c=cn.getText();
        String coma;
        StringTokenizer st1 = new StringTokenizer(c,",",true);
        ArrayList<Double> xi=new ArrayList();
        ArrayList<Double> x=new ArrayList();
        ArrayList<Double> y=new ArrayList();
        while (st1.hasMoreTokens()) {
            coma=st1.nextToken();
            if(!coma.equals(",")){
                xi.add(Double.parseDouble(coma));
                System.out.println(xi.get(i));
                i++;
            }
        }
        for(int m=0;m<xi.size();m++){
            y.add(inicio);
            if(esMultiplo(inicio.intValue(),k)){
               x.add(xi.get(m));
               if(xi.get(m)<j){
                   s=xi.get(m).intValue();
               }
               if(f<xi.get(m)){
                   f=xi.get(m).intValue();
               }
            }
            inicio++;
        }
        j=inicio.intValue();
        inicio=Double.parseDouble(origen.getText());
        graficar("Diezmación",x,inicio,j,s,f);
        resd.setText(x.toString());
    }
    
    public static boolean esMultiplo(int n1,int n2){
    	if (n1%n2==0)
    		return true;
    	else
    		return false;
    }
    
    public void interpolar(){
        int k=Integer.parseInt(nd.getText());
        int fin=0;
        Double s=0.0;
        Double inicio=Double.parseDouble(origen.getText());
        Integer i=0;
        String c=cn.getText();
        String coma;
        StringTokenizer st1 = new StringTokenizer(c,",",true);
        ArrayList<Double> xi=new ArrayList();
        ArrayList<Double> x=new ArrayList();
        ArrayList<Double> y=new ArrayList();
        while (st1.hasMoreTokens()) {
            coma=st1.nextToken();
            if(!coma.equals(",")){
                xi.add(Double.parseDouble(coma));
                System.out.println(xi.get(i));
                i++;
            }
        }
        for(int m=0;m<xi.size();m++){
            if(m<xi.size()-1){
            s=Math.abs(xi.get(m)-xi.get(m+1))/k;
            if(xi.get(m)<xi.get(m+1)){
                s=s+xi.get(m);
                x.add(xi.get(m));
                x.add(s);
            }else{
                s=s-xi.get(m);
                x.add(xi.get(m));
                x.add(s);
            }
            y.add(inicio);
            inicio++;
            }
        }
        graficar("Interpolación",x,inicio,fin,fin,i);
        resi.setText(x.toString());
    }

    
    public void graficar(String t, ArrayList<Double> xi,double or, int f,int ory,int fy){
        	final XYSeries serie1 = new XYSeries(t);
                int aux = 0;
                for(double d:xi){
                    serie1.add(or,xi.get(aux));
                    aux++;
                    or++;
                }
		
/*		final XYSeries serie2 = new XYSeries("Jaime Alguersuari");
		serie2.add(1, 133.16);
		serie2.add(2, 132.32);
		serie2.add(3, 129.86);
		serie2.add(4, 128.02);
		serie2.add(5, 132.45);
*/		
		final XYSeriesCollection collection = new XYSeriesCollection();
		collection.addSeries(serie1);
//		collection.addSeries(serie2);
		
		try {
			final JFreeChart grafica = crearGrafica(collection,or,f,ory,fy);
                        jPanel1.setLayout(new java.awt.BorderLayout());
                        ChartPanel chartPanel = new ChartPanel(grafica);   
                        XYPlot plot=grafica.getXYPlot();
                        XYLineAndShapeRenderer renderer=new XYLineAndShapeRenderer();
                        renderer.setSeriesLinesVisible(0, false);
                        renderer.setSeriesShapesVisible(0, true);
                        renderer.setSeriesLinesVisible(1, true);
                        renderer.setSeriesShapesVisible(1, false); 
                        plot.setRenderer(renderer);
                        jPanel1.add(chartPanel,BorderLayout.CENTER);
                        jPanel1.validate();
		} catch (Exception e) {
			e.printStackTrace();
		}

}
    
    	public  JFreeChart crearGrafica(XYSeriesCollection dataset,double i,int f,int iy,int fy) {
 
		final JFreeChart chart = ChartFactory.createXYLineChart("Tiempos de entrenamientos", "Vuelta", "Tiempo (segundos)", 
				dataset,
				PlotOrientation.VERTICAL, 
				true, // uso de leyenda
				false, // uso de tooltips  
				false // uso de urls
 				);
		// color de fondo de la gráfica
 
		final XYPlot plot = (XYPlot) chart.getPlot();
 
		final NumberAxis domainAxis = (NumberAxis)plot.getDomainAxis();
		configurarDomainAxis(domainAxis,i,f);
		
		final NumberAxis rangeAxis = (NumberAxis)plot.getRangeAxis();
		configurarRangeAxis(rangeAxis,iy,fy);
 
		final XYLineAndShapeRenderer renderer = (XYLineAndShapeRenderer)plot.getRenderer();
		configurarRendered(renderer);
 
		return chart;
	}
	
	// configuramos el contenido del gráfico (damos un color a las líneas que sirven de guía)
	
	// configuramos el eje X de la gráfica (se muestran números enteros y de uno en uno)
	private void configurarDomainAxis (NumberAxis domainAxis, double i,int f) {
		domainAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());
		domainAxis.setTickUnit(new NumberTickUnit(0.5));
                domainAxis.setRange(i,f);
	}
	
	// configuramos el eje y de la gráfica (números enteros de dos en dos y rango entre 120 y 135)
	private void configurarRangeAxis (NumberAxis rangeAxis,int iy,int fy) {
		rangeAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());
		rangeAxis.setTickUnit(new NumberTickUnit(0.5));
		rangeAxis.setRange(iy, fy);
	}
	
	// configuramos las líneas de las series (añadimos un círculo en los puntos y asignamos el color de cada serie)
	private void configurarRendered (XYLineAndShapeRenderer renderer) {
		renderer.setSeriesShapesVisible(0, true);
		renderer.setSeriesShapesVisible(1, true);
	}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diezmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diezmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diezmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diezmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diezmacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cn;
    private javax.swing.JButton diezmar;
    private javax.swing.JButton interpolar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nd;
    private javax.swing.JTextField origen;
    private javax.swing.JTextArea resd;
    private javax.swing.JTextArea resi;
    // End of variables declaration//GEN-END:variables
}
